services:
  bullboard:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: ''
    restart: always
